// AUTO-GENERATED by scripts/gen-portfolio.mjs — do not edit by hand.
// Run `node scripts/gen-portfolio.mjs` to regenerate from public/og/images/.

export type GalleryItem = {
  title: string;
  category: string;
  thumb: string;
  full: string;
  w: number;
  h: number;
};

export type GalleryCategory = { label: string; blurb: string; count: number };

export const galleryCategories: GalleryCategory[] = [
  {
    "label": "Social Media",
    "blurb": "Campaign creatives and on-brand social posts.",
    "count": 23
  },
  {
    "label": "Wall Posters",
    "blurb": "Large-format wall and pillar branding for clinics.",
    "count": 21
  },
  {
    "label": "Standees",
    "blurb": "Floor standees and roll-up display banners.",
    "count": 12
  },
  {
    "label": "Letterheads & Stationery",
    "blurb": "Letterheads, pamphlets and brand stationery.",
    "count": 9
  },
  {
    "label": "Patient Files",
    "blurb": "Branded patient record folders and inserts.",
    "count": 4
  },
  {
    "label": "QR & Branding",
    "blurb": "QR standees and quick brand touchpoints.",
    "count": 3
  },
  {
    "label": "Posters & Creatives",
    "blurb": "Treatment posters, pamphlets and print creatives.",
    "count": 47
  }
];

export const galleryItems: GalleryItem[] = [
  {
    "title": "Awareness Post",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/awareness-post-0.webp",
    "full": "/portfolio/full/root/awareness-post-0.webp",
    "w": 720,
    "h": 1018
  },
  {
    "title": "CHEMICAL PEEL",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/chemical-peel-copy-1.webp",
    "full": "/portfolio/full/root/chemical-peel-copy-1.webp",
    "w": 720,
    "h": 1080
  },
  {
    "title": "Chemical peel",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/chemical-peel-a1-size-2.webp",
    "full": "/portfolio/full/root/chemical-peel-a1-size-2.webp",
    "w": 720,
    "h": 1019
  },
  {
    "title": "Chemical peeling",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/chemical-peeling-3.webp",
    "full": "/portfolio/full/root/chemical-peeling-3.webp",
    "w": 720,
    "h": 405
  },
  {
    "title": "Clinic Timing Dr R Madhavan Coimbatore",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/clinic-timing-dr-r-madhavan-coimbatore-4.webp",
    "full": "/portfolio/full/root/clinic-timing-dr-r-madhavan-coimbatore-4.webp",
    "w": 720,
    "h": 1280
  },
  {
    "title": "Dr Indubala Pamplet 1",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/dr-indubala-pamplet-1-5.webp",
    "full": "/portfolio/full/root/dr-indubala-pamplet-1-5.webp",
    "w": 720,
    "h": 1012
  },
  {
    "title": "Dr Indubala Pamplet back side",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/dr-indubala-pamplet-back-side-6.webp",
    "full": "/portfolio/full/root/dr-indubala-pamplet-back-side-6.webp",
    "w": 720,
    "h": 1012
  },
  {
    "title": "Dr Jayalakshmi 1",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/dr-jayalakshmi-1-7.webp",
    "full": "/portfolio/full/root/dr-jayalakshmi-1-7.webp",
    "w": 720,
    "h": 386
  },
  {
    "title": "Dr meena",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/dr-meena-8.webp",
    "full": "/portfolio/full/root/dr-meena-8.webp",
    "w": 720,
    "h": 597
  },
  {
    "title": "Dr Nivedhan standee",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/dr-nivedhan-standee-9.webp",
    "full": "/portfolio/full/root/dr-nivedhan-standee-9.webp",
    "w": 720,
    "h": 1728
  },
  {
    "title": "Fairness awarness",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/fairness-awarness-10.webp",
    "full": "/portfolio/full/root/fairness-awarness-10.webp",
    "w": 720,
    "h": 1280
  },
  {
    "title": "Flex print for free camp",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/flex-print-for-free-camp-11.webp",
    "full": "/portfolio/full/root/flex-print-for-free-camp-11.webp",
    "w": 720,
    "h": 360
  },
  {
    "title": "Frozen Shoulder",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/frozen-shoulder-12.webp",
    "full": "/portfolio/full/root/frozen-shoulder-12.webp",
    "w": 720,
    "h": 907
  },
  {
    "title": "Gift coupon",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/gift-coupon-13.webp",
    "full": "/portfolio/full/root/gift-coupon-13.webp",
    "w": 720,
    "h": 356
  },
  {
    "title": "Glutathione DRIP",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/glutathione-drip-14.webp",
    "full": "/portfolio/full/root/glutathione-drip-14.webp",
    "w": 720,
    "h": 1280
  },
  {
    "title": "Google Review",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/google-review-15.webp",
    "full": "/portfolio/full/root/google-review-15.webp",
    "w": 720,
    "h": 1280
  },
  {
    "title": "Hair loss 3",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/hair-loss-3-16.webp",
    "full": "/portfolio/full/root/hair-loss-3-16.webp",
    "w": 720,
    "h": 720
  },
  {
    "title": "Kids mockup",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/kids-mockup-17.webp",
    "full": "/portfolio/full/root/kids-mockup-17.webp",
    "w": 720,
    "h": 716
  },
  {
    "title": "LASER HAIR REDUCTION",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/laser-hair-reduction-18.webp",
    "full": "/portfolio/full/root/laser-hair-reduction-18.webp",
    "w": 720,
    "h": 405
  },
  {
    "title": "LASER Tattoo Removal",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/laser-tattoo-removal-19.webp",
    "full": "/portfolio/full/root/laser-tattoo-removal-19.webp",
    "w": 720,
    "h": 405
  },
  {
    "title": "Laser treatments",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/laser-treatments-20.webp",
    "full": "/portfolio/full/root/laser-treatments-20.webp",
    "w": 720,
    "h": 1280
  },
  {
    "title": "MG CLINIC",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/mg-clinic-21.webp",
    "full": "/portfolio/full/root/mg-clinic-21.webp",
    "w": 720,
    "h": 296
  },
  {
    "title": "MG Skin & ENT Clinic - Qr code",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/mg-skin-ent-clinic-qr-code-22.webp",
    "full": "/portfolio/full/root/mg-skin-ent-clinic-qr-code-22.webp",
    "w": 720,
    "h": 1018
  },
  {
    "title": "MNRF",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/mnrf-23.webp",
    "full": "/portfolio/full/root/mnrf-23.webp",
    "w": 720,
    "h": 1280
  },
  {
    "title": "Mock up",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/mock-up-24.webp",
    "full": "/portfolio/full/root/mock-up-24.webp",
    "w": 720,
    "h": 540
  },
  {
    "title": "Mockup",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/mockup-25.webp",
    "full": "/portfolio/full/root/mockup-25.webp",
    "w": 720,
    "h": 480
  },
  {
    "title": "MOCKUP 1",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/mockup-1-26.webp",
    "full": "/portfolio/full/root/mockup-1-26.webp",
    "w": 720,
    "h": 480
  },
  {
    "title": "MOCKUP 2",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/mockup-2-27.webp",
    "full": "/portfolio/full/root/mockup-2-27.webp",
    "w": 720,
    "h": 480
  },
  {
    "title": "MOCKUP 3",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/mockup-3-28.webp",
    "full": "/portfolio/full/root/mockup-3-28.webp",
    "w": 720,
    "h": 479
  },
  {
    "title": "Navaladi Skin Clinic 1",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/navaladi-skin-clinic-1-29.webp",
    "full": "/portfolio/full/root/navaladi-skin-clinic-1-29.webp",
    "w": 720,
    "h": 480
  },
  {
    "title": "New year mg skin clinic",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/new-year-mg-skin-clinic-30.webp",
    "full": "/portfolio/full/root/new-year-mg-skin-clinic-30.webp",
    "w": 720,
    "h": 900
  },
  {
    "title": "Plasma treatment for face 1",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/plasma-treatment-for-face-1-copy-31.webp",
    "full": "/portfolio/full/root/plasma-treatment-for-face-1-copy-31.webp",
    "w": 720,
    "h": 1080
  },
  {
    "title": "PRP INJECTION -",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/prp-injection-36x32-copy-32.webp",
    "full": "/portfolio/full/root/prp-injection-36x32-copy-32.webp",
    "w": 720,
    "h": 798
  },
  {
    "title": "PRP x GFC FOR HAIR option 1",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/prp-x-gfc-for-hair-option-1-copy-33.webp",
    "full": "/portfolio/full/root/prp-x-gfc-for-hair-option-1-copy-33.webp",
    "w": 720,
    "h": 1080
  },
  {
    "title": "Revive",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/revive-34.webp",
    "full": "/portfolio/full/root/revive-34.webp",
    "w": 720,
    "h": 1019
  },
  {
    "title": "Skin hair and nail",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/skin-hair-and-nail-35.webp",
    "full": "/portfolio/full/root/skin-hair-and-nail-35.webp",
    "w": 720,
    "h": 1019
  },
  {
    "title": "Skin lightening treatment",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/skin-lightening-treatment-36.webp",
    "full": "/portfolio/full/root/skin-lightening-treatment-36.webp",
    "w": 720,
    "h": 1022
  },
  {
    "title": "Skinmatics pamplet tamil",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/skinmatics-pamplet-tamil-37.webp",
    "full": "/portfolio/full/root/skinmatics-pamplet-tamil-37.webp",
    "w": 720,
    "h": 1022
  },
  {
    "title": "Smooth Refined Renewed",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/smooth-refined-renewed-38.webp",
    "full": "/portfolio/full/root/smooth-refined-renewed-38.webp",
    "w": 720,
    "h": 1280
  },
  {
    "title": "Tennis Elbow - Fleming",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/tennis-elbow-fleming-39.webp",
    "full": "/portfolio/full/root/tennis-elbow-fleming-39.webp",
    "w": 720,
    "h": 907
  },
  {
    "title": "Treatement POSTER",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/treatement-poster-17x22-40.webp",
    "full": "/portfolio/full/root/treatement-poster-17x22-40.webp",
    "w": 720,
    "h": 823
  },
  {
    "title": "VAGINAL RF Tightening",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/vaginal-rf-tightening-41.webp",
    "full": "/portfolio/full/root/vaginal-rf-tightening-41.webp",
    "w": 720,
    "h": 1280
  },
  {
    "title": "Visiting card front",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/visiting-card-front-42.webp",
    "full": "/portfolio/full/root/visiting-card-front-42.webp",
    "w": 720,
    "h": 432
  },
  {
    "title": "Visiting card",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/visiting-card-43.webp",
    "full": "/portfolio/full/root/visiting-card-43.webp",
    "w": 720,
    "h": 432
  },
  {
    "title": "Wall 2 size chnaged",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/wall-2-size-chnaged-44.webp",
    "full": "/portfolio/full/root/wall-2-size-chnaged-44.webp",
    "w": 720,
    "h": 514
  },
  {
    "title": "Posters & Creatives — Mockup",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/whatsapp-image-2025-01-06-at-19-18-56-231e744f-45.webp",
    "full": "/portfolio/full/root/whatsapp-image-2025-01-06-at-19-18-56-231e744f-45.webp",
    "w": 720,
    "h": 216
  },
  {
    "title": "Posters & Creatives — Mockup",
    "category": "Posters & Creatives",
    "thumb": "/portfolio/thumbs/root/whatsapp-image-2026-02-11-at-11-04-19-am-46.webp",
    "full": "/portfolio/full/root/whatsapp-image-2026-02-11-at-11-04-19-am-46.webp",
    "w": 720,
    "h": 1081
  },
  {
    "title": "Aesthetic 2 back side",
    "category": "Letterheads & Stationery",
    "thumb": "/portfolio/thumbs/new-folder/aesthetic-2-back-side-0.webp",
    "full": "/portfolio/full/new-folder/aesthetic-2-back-side-0.webp",
    "w": 720,
    "h": 1018
  },
  {
    "title": "Aesthetic 2",
    "category": "Letterheads & Stationery",
    "thumb": "/portfolio/thumbs/new-folder/aesthetic-2-1.webp",
    "full": "/portfolio/full/new-folder/aesthetic-2-1.webp",
    "w": 720,
    "h": 1018
  },
  {
    "title": "Dr Kanaks Enivironment day",
    "category": "Letterheads & Stationery",
    "thumb": "/portfolio/thumbs/new-folder/dr-kanaks-enivironment-day-2.webp",
    "full": "/portfolio/full/new-folder/dr-kanaks-enivironment-day-2.webp",
    "w": 720,
    "h": 1018
  },
  {
    "title": "Dr Kanaks summer sun screen",
    "category": "Letterheads & Stationery",
    "thumb": "/portfolio/thumbs/new-folder/dr-kanaks-summer-sun-screen-3.webp",
    "full": "/portfolio/full/new-folder/dr-kanaks-summer-sun-screen-3.webp",
    "w": 720,
    "h": 1018
  },
  {
    "title": "Dr Kanaks Womens day 1",
    "category": "Letterheads & Stationery",
    "thumb": "/portfolio/thumbs/new-folder/dr-kanaks-womens-day-1-4.webp",
    "full": "/portfolio/full/new-folder/dr-kanaks-womens-day-1-4.webp",
    "w": 720,
    "h": 1018
  },
  {
    "title": "Independnce day",
    "category": "Letterheads & Stationery",
    "thumb": "/portfolio/thumbs/new-folder/independnce-day-5.webp",
    "full": "/portfolio/full/new-folder/independnce-day-5.webp",
    "w": 720,
    "h": 1018
  },
  {
    "title": "Janani - Letter head",
    "category": "Letterheads & Stationery",
    "thumb": "/portfolio/thumbs/new-folder/janani-letter-head-6.webp",
    "full": "/portfolio/full/new-folder/janani-letter-head-6.webp",
    "w": 720,
    "h": 1018
  },
  {
    "title": "Letter head back side",
    "category": "Letterheads & Stationery",
    "thumb": "/portfolio/thumbs/new-folder/letter-head-back-side-7.webp",
    "full": "/portfolio/full/new-folder/letter-head-back-side-7.webp",
    "w": 720,
    "h": 1018
  },
  {
    "title": "Letter head",
    "category": "Letterheads & Stationery",
    "thumb": "/portfolio/thumbs/new-folder/letter-head-8.webp",
    "full": "/portfolio/full/new-folder/letter-head-8.webp",
    "w": 720,
    "h": 1018
  },
  {
    "title": "K mockup",
    "category": "Patient Files",
    "thumb": "/portfolio/thumbs/patient-file/k-mockup-0.webp",
    "full": "/portfolio/full/patient-file/k-mockup-0.webp",
    "w": 720,
    "h": 480
  },
  {
    "title": "O7D9SB1",
    "category": "Patient Files",
    "thumb": "/portfolio/thumbs/patient-file/o7d9sb1-1.webp",
    "full": "/portfolio/full/patient-file/o7d9sb1-1.webp",
    "w": 720,
    "h": 720
  },
  {
    "title": "Patient File Dermalaya 2",
    "category": "Patient Files",
    "thumb": "/portfolio/thumbs/patient-file/patient-file-dermalaya-2-2.webp",
    "full": "/portfolio/full/patient-file/patient-file-dermalaya-2-2.webp",
    "w": 720,
    "h": 509
  },
  {
    "title": "Patient file",
    "category": "Patient Files",
    "thumb": "/portfolio/thumbs/patient-file/patient-file-3.webp",
    "full": "/portfolio/full/patient-file/patient-file-3.webp",
    "w": 720,
    "h": 448
  },
  {
    "title": "QR & Branding — Mockup",
    "category": "QR & Branding",
    "thumb": "/portfolio/thumbs/qr-code-scanner/chatgpt-image-jun-4-2026-05-40-35-pm-0.webp",
    "full": "/portfolio/full/qr-code-scanner/chatgpt-image-jun-4-2026-05-40-35-pm-0.webp",
    "w": 720,
    "h": 900
  },
  {
    "title": "QR & Branding — Mockup",
    "category": "QR & Branding",
    "thumb": "/portfolio/thumbs/qr-code-scanner/chatgpt-image-may-22-2026-12-19-41-pm-1.webp",
    "full": "/portfolio/full/qr-code-scanner/chatgpt-image-may-22-2026-12-19-41-pm-1.webp",
    "w": 720,
    "h": 1019
  },
  {
    "title": "Dr balagapanthy mockp jpg",
    "category": "QR & Branding",
    "thumb": "/portfolio/thumbs/qr-code-scanner/dr-balagapanthy-mockp-jpg-2.webp",
    "full": "/portfolio/full/qr-code-scanner/dr-balagapanthy-mockp-jpg-2.webp",
    "w": 720,
    "h": 557
  },
  {
    "title": "Acne 1",
    "category": "Social Media",
    "thumb": "/portfolio/thumbs/social-media/acne-1-0.webp",
    "full": "/portfolio/full/social-media/acne-1-0.webp",
    "w": 720,
    "h": 720
  },
  {
    "title": "Acne scar removal",
    "category": "Social Media",
    "thumb": "/portfolio/thumbs/social-media/acne-scar-removal-1.webp",
    "full": "/portfolio/full/social-media/acne-scar-removal-1.webp",
    "w": 720,
    "h": 720
  },
  {
    "title": "Acne Scar Treatment",
    "category": "Social Media",
    "thumb": "/portfolio/thumbs/social-media/acne-scar-treatment-2.webp",
    "full": "/portfolio/full/social-media/acne-scar-treatment-2.webp",
    "w": 720,
    "h": 720
  },
  {
    "title": "Chemical peel 1",
    "category": "Social Media",
    "thumb": "/portfolio/thumbs/social-media/chemical-peel-1-3.webp",
    "full": "/portfolio/full/social-media/chemical-peel-1-3.webp",
    "w": 720,
    "h": 720
  },
  {
    "title": "Chemical peel",
    "category": "Social Media",
    "thumb": "/portfolio/thumbs/social-media/chemical-peel-4.webp",
    "full": "/portfolio/full/social-media/chemical-peel-4.webp",
    "w": 720,
    "h": 720
  },
  {
    "title": "Co2RE Intima",
    "category": "Social Media",
    "thumb": "/portfolio/thumbs/social-media/co2re-intima-5.webp",
    "full": "/portfolio/full/social-media/co2re-intima-5.webp",
    "w": 720,
    "h": 720
  },
  {
    "title": "Dark Circles 1",
    "category": "Social Media",
    "thumb": "/portfolio/thumbs/social-media/dark-circles-1-6.webp",
    "full": "/portfolio/full/social-media/dark-circles-1-6.webp",
    "w": 720,
    "h": 720
  },
  {
    "title": "Dr Rajani women's day poster (2)",
    "category": "Social Media",
    "thumb": "/portfolio/thumbs/social-media/dr-rajani-women-s-day-poster-2-7.webp",
    "full": "/portfolio/full/social-media/dr-rajani-women-s-day-poster-2-7.webp",
    "w": 720,
    "h": 720
  },
  {
    "title": "Dr Ranjani Offer 1 poster",
    "category": "Social Media",
    "thumb": "/portfolio/thumbs/social-media/dr-ranjani-offer-1-poster-8.webp",
    "full": "/portfolio/full/social-media/dr-ranjani-offer-1-poster-8.webp",
    "w": 720,
    "h": 720
  },
  {
    "title": "Dr Ranjani Women's day poster",
    "category": "Social Media",
    "thumb": "/portfolio/thumbs/social-media/dr-ranjani-women-s-day-poster-9.webp",
    "full": "/portfolio/full/social-media/dr-ranjani-women-s-day-poster-9.webp",
    "w": 720,
    "h": 720
  },
  {
    "title": "Dr Rohit kumar",
    "category": "Social Media",
    "thumb": "/portfolio/thumbs/social-media/dr-rohit-kumar-10.webp",
    "full": "/portfolio/full/social-media/dr-rohit-kumar-10.webp",
    "w": 720,
    "h": 720
  },
  {
    "title": "Fractional co2 laser",
    "category": "Social Media",
    "thumb": "/portfolio/thumbs/social-media/fractional-co2-laser-11.webp",
    "full": "/portfolio/full/social-media/fractional-co2-laser-11.webp",
    "w": 720,
    "h": 775
  },
  {
    "title": "Hair Fall 2",
    "category": "Social Media",
    "thumb": "/portfolio/thumbs/social-media/hair-fall-2-12.webp",
    "full": "/portfolio/full/social-media/hair-fall-2-12.webp",
    "w": 720,
    "h": 720
  },
  {
    "title": "Laser hair reduction 1",
    "category": "Social Media",
    "thumb": "/portfolio/thumbs/social-media/laser-hair-reduction-1-13.webp",
    "full": "/portfolio/full/social-media/laser-hair-reduction-1-13.webp",
    "w": 720,
    "h": 720
  },
  {
    "title": "Laser hair removal 1",
    "category": "Social Media",
    "thumb": "/portfolio/thumbs/social-media/laser-hair-removal-1-14.webp",
    "full": "/portfolio/full/social-media/laser-hair-removal-1-14.webp",
    "w": 720,
    "h": 720
  },
  {
    "title": "LASER TATTOO REMOVAL 36x29 5",
    "category": "Social Media",
    "thumb": "/portfolio/thumbs/social-media/laser-tattoo-removal-36x29-5-copy-copy-15.webp",
    "full": "/portfolio/full/social-media/laser-tattoo-removal-36x29-5-copy-copy-15.webp",
    "w": 720,
    "h": 746
  },
  {
    "title": "Lipolysis",
    "category": "Social Media",
    "thumb": "/portfolio/thumbs/social-media/lipolysis-16.webp",
    "full": "/portfolio/full/social-media/lipolysis-16.webp",
    "w": 720,
    "h": 720
  },
  {
    "title": "Miladi nabi",
    "category": "Social Media",
    "thumb": "/portfolio/thumbs/social-media/miladi-nabi-17.webp",
    "full": "/portfolio/full/social-media/miladi-nabi-17.webp",
    "w": 720,
    "h": 720
  },
  {
    "title": "Nose Piercing",
    "category": "Social Media",
    "thumb": "/portfolio/thumbs/social-media/nose-piercing-18.webp",
    "full": "/portfolio/full/social-media/nose-piercing-18.webp",
    "w": 720,
    "h": 720
  },
  {
    "title": "Pigmentation",
    "category": "Social Media",
    "thumb": "/portfolio/thumbs/social-media/pigmentation-19.webp",
    "full": "/portfolio/full/social-media/pigmentation-19.webp",
    "w": 720,
    "h": 720
  },
  {
    "title": "Prp",
    "category": "Social Media",
    "thumb": "/portfolio/thumbs/social-media/prp-20.webp",
    "full": "/portfolio/full/social-media/prp-20.webp",
    "w": 720,
    "h": 720
  },
  {
    "title": "Sunscreen 1",
    "category": "Social Media",
    "thumb": "/portfolio/thumbs/social-media/sunscreen-1-21.webp",
    "full": "/portfolio/full/social-media/sunscreen-1-21.webp",
    "w": 720,
    "h": 720
  },
  {
    "title": "Vitiligo 2",
    "category": "Social Media",
    "thumb": "/portfolio/thumbs/social-media/vitiligo-2-22.webp",
    "full": "/portfolio/full/social-media/vitiligo-2-22.webp",
    "w": 720,
    "h": 720
  },
  {
    "title": "Standees — Mockup",
    "category": "Standees",
    "thumb": "/portfolio/thumbs/standee/2aa72f7c-c49e-42f0-a70a-a8c5c8fb272b-0.webp",
    "full": "/portfolio/full/standee/2aa72f7c-c49e-42f0-a70a-a8c5c8fb272b-0.webp",
    "w": 720,
    "h": 1440
  },
  {
    "title": "Acne scar standee",
    "category": "Standees",
    "thumb": "/portfolio/thumbs/standee/acne-scar-standee-1.webp",
    "full": "/portfolio/full/standee/acne-scar-standee-1.webp",
    "w": 720,
    "h": 1440
  },
  {
    "title": "Acne",
    "category": "Standees",
    "thumb": "/portfolio/thumbs/standee/acne-2.webp",
    "full": "/portfolio/full/standee/acne-2.webp",
    "w": 720,
    "h": 1080
  },
  {
    "title": "All treatments 1",
    "category": "Standees",
    "thumb": "/portfolio/thumbs/standee/all-treatments-1-3.webp",
    "full": "/portfolio/full/standee/all-treatments-1-3.webp",
    "w": 720,
    "h": 1080
  },
  {
    "title": "Standees — Mockup",
    "category": "Standees",
    "thumb": "/portfolio/thumbs/standee/chatgpt-image-jun-9-2026-10-43-48-am-4.webp",
    "full": "/portfolio/full/standee/chatgpt-image-jun-9-2026-10-43-48-am-4.webp",
    "w": 720,
    "h": 1440
  },
  {
    "title": "Hair",
    "category": "Standees",
    "thumb": "/portfolio/thumbs/standee/hair-5.webp",
    "full": "/portfolio/full/standee/hair-5.webp",
    "w": 720,
    "h": 1080
  },
  {
    "title": "Mock up one",
    "category": "Standees",
    "thumb": "/portfolio/thumbs/standee/mock-up-one-6.webp",
    "full": "/portfolio/full/standee/mock-up-one-6.webp",
    "w": 720,
    "h": 549
  },
  {
    "title": "Prathiba mockup",
    "category": "Standees",
    "thumb": "/portfolio/thumbs/standee/prathiba-mockup-7.webp",
    "full": "/portfolio/full/standee/prathiba-mockup-7.webp",
    "w": 720,
    "h": 540
  },
  {
    "title": "SB SKIN CLINIC",
    "category": "Standees",
    "thumb": "/portfolio/thumbs/standee/sb-skin-clinic-8.webp",
    "full": "/portfolio/full/standee/sb-skin-clinic-8.webp",
    "w": 720,
    "h": 1440
  },
  {
    "title": "Standee -",
    "category": "Standees",
    "thumb": "/portfolio/thumbs/standee/standee-4x2-copy-9.webp",
    "full": "/portfolio/full/standee/standee-4x2-copy-9.webp",
    "w": 720,
    "h": 1152
  },
  {
    "title": "STANDEE MOCKUP",
    "category": "Standees",
    "thumb": "/portfolio/thumbs/standee/standee-mockup-10.webp",
    "full": "/portfolio/full/standee/standee-mockup-10.webp",
    "w": 720,
    "h": 720
  },
  {
    "title": "Standee",
    "category": "Standees",
    "thumb": "/portfolio/thumbs/standee/standee-11.webp",
    "full": "/portfolio/full/standee/standee-11.webp",
    "w": 720,
    "h": 1227
  },
  {
    "title": "MOCKUP 1",
    "category": "Wall Posters",
    "thumb": "/portfolio/thumbs/wall-poster/5x5-mockup-1-0.webp",
    "full": "/portfolio/full/wall-poster/5x5-mockup-1-0.webp",
    "w": 720,
    "h": 720
  },
  {
    "title": "MOCKUP",
    "category": "Wall Posters",
    "thumb": "/portfolio/thumbs/wall-poster/5x5-mockup-1.webp",
    "full": "/portfolio/full/wall-poster/5x5-mockup-1.webp",
    "w": 720,
    "h": 1080
  },
  {
    "title": "Acne scar",
    "category": "Wall Posters",
    "thumb": "/portfolio/thumbs/wall-poster/acne-scar-2.webp",
    "full": "/portfolio/full/wall-poster/acne-scar-2.webp",
    "w": 720,
    "h": 1022
  },
  {
    "title": "Wall Posters — Mockup",
    "category": "Wall Posters",
    "thumb": "/portfolio/thumbs/wall-poster/chatgpt-image-jun-9-2026-11-00-15-am-3.webp",
    "full": "/portfolio/full/wall-poster/chatgpt-image-jun-9-2026-11-00-15-am-3.webp",
    "w": 720,
    "h": 480
  },
  {
    "title": "Wall Posters — Mockup",
    "category": "Wall Posters",
    "thumb": "/portfolio/thumbs/wall-poster/chatgpt-image-jun-9-2026-11-05-11-am-4.webp",
    "full": "/portfolio/full/wall-poster/chatgpt-image-jun-9-2026-11-05-11-am-4.webp",
    "w": 720,
    "h": 480
  },
  {
    "title": "CO2 Laser Treatment",
    "category": "Wall Posters",
    "thumb": "/portfolio/thumbs/wall-poster/co2-laser-treatment-5.webp",
    "full": "/portfolio/full/wall-poster/co2-laser-treatment-5.webp",
    "w": 720,
    "h": 1080
  },
  {
    "title": "Dr Amudha light",
    "category": "Wall Posters",
    "thumb": "/portfolio/thumbs/wall-poster/dr-amudha-copy-light-6.webp",
    "full": "/portfolio/full/wall-poster/dr-amudha-copy-light-6.webp",
    "w": 720,
    "h": 1019
  },
  {
    "title": "Dr Indhumathi",
    "category": "Wall Posters",
    "thumb": "/portfolio/thumbs/wall-poster/dr-indhumathi-7.webp",
    "full": "/portfolio/full/wall-poster/dr-indhumathi-7.webp",
    "w": 720,
    "h": 1019
  },
  {
    "title": "Dr Jayanthinie",
    "category": "Wall Posters",
    "thumb": "/portfolio/thumbs/wall-poster/dr-jayanthinie-8.webp",
    "full": "/portfolio/full/wall-poster/dr-jayanthinie-8.webp",
    "w": 720,
    "h": 1018
  },
  {
    "title": "Excimer-1-1-orig orig",
    "category": "Wall Posters",
    "thumb": "/portfolio/thumbs/wall-poster/excimer-1-1-orig-orig-9.webp",
    "full": "/portfolio/full/wall-poster/excimer-1-1-orig-orig-9.webp",
    "w": 640,
    "h": 800
  },
  {
    "title": "First glass - entrance 1",
    "category": "Wall Posters",
    "thumb": "/portfolio/thumbs/wall-poster/first-glass-entrance-1-10.webp",
    "full": "/portfolio/full/wall-poster/first-glass-entrance-1-10.webp",
    "w": 720,
    "h": 579
  },
  {
    "title": "GLASS PROMOTION LHR 31",
    "category": "Wall Posters",
    "thumb": "/portfolio/thumbs/wall-poster/glass-promotion-lhr-31-3x27-6-copy-11.webp",
    "full": "/portfolio/full/wall-poster/glass-promotion-lhr-31-3x27-6-copy-11.webp",
    "w": 720,
    "h": 816
  },
  {
    "title": "GLASS Sticker",
    "category": "Wall Posters",
    "thumb": "/portfolio/thumbs/wall-poster/glass-sticker-12.webp",
    "full": "/portfolio/full/wall-poster/glass-sticker-12.webp",
    "w": 720,
    "h": 678
  },
  {
    "title": "Knee pain",
    "category": "Wall Posters",
    "thumb": "/portfolio/thumbs/wall-poster/knee-pain-13.webp",
    "full": "/portfolio/full/wall-poster/knee-pain-13.webp",
    "w": 720,
    "h": 907
  },
  {
    "title": "Laser Hair reduction",
    "category": "Wall Posters",
    "thumb": "/portfolio/thumbs/wall-poster/laser-hair-reduction-copy-14.webp",
    "full": "/portfolio/full/wall-poster/laser-hair-reduction-copy-14.webp",
    "w": 720,
    "h": 1080
  },
  {
    "title": "Laser hair removal",
    "category": "Wall Posters",
    "thumb": "/portfolio/thumbs/wall-poster/laser-hair-removal-15.webp",
    "full": "/portfolio/full/wall-poster/laser-hair-removal-15.webp",
    "w": 720,
    "h": 1019
  },
  {
    "title": "LHR - Dr",
    "category": "Wall Posters",
    "thumb": "/portfolio/thumbs/wall-poster/lhr-dr-16.webp",
    "full": "/portfolio/full/wall-poster/lhr-dr-16.webp",
    "w": 720,
    "h": 1019
  },
  {
    "title": "PILLAR 1",
    "category": "Wall Posters",
    "thumb": "/portfolio/thumbs/wall-poster/pillar-1-17.webp",
    "full": "/portfolio/full/wall-poster/pillar-1-17.webp",
    "w": 720,
    "h": 1280
  },
  {
    "title": "PILLLAR 2",
    "category": "Wall Posters",
    "thumb": "/portfolio/thumbs/wall-poster/pilllar-2-18.webp",
    "full": "/portfolio/full/wall-poster/pilllar-2-18.webp",
    "w": 720,
    "h": 1280
  },
  {
    "title": "Rohit kumar - mockup",
    "category": "Wall Posters",
    "thumb": "/portfolio/thumbs/wall-poster/rohit-kumar-mockup-19.webp",
    "full": "/portfolio/full/wall-poster/rohit-kumar-mockup-19.webp",
    "w": 720,
    "h": 1249
  },
  {
    "title": "Shobi meena",
    "category": "Wall Posters",
    "thumb": "/portfolio/thumbs/wall-poster/shobi-meena-20.webp",
    "full": "/portfolio/full/wall-poster/shobi-meena-20.webp",
    "w": 720,
    "h": 540
  }
];
